services:
    # Default configuration for services in *this* bundle
    _defaults:
        autowire: true
        autoconfigure: true

    # Automatically register all classes in src/ as services
    morfeditorial\TelegramBotBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../TelegramBotBundle.php'
            - '../../Resources/'

    # Register the TelegramClient as a service
    morfeditorial\TelegramBotBundle\Client\TelegramClient:
        arguments:
            $httpClient: '@http_client'
            $botToken: '%telegram_bot.token%'
        public: true
