services:
    # Default configuration for services in *this* bundle
    _defaults:
        autowire: true
        autoconfigure: true

    # Register the TelegramClient as a service
    TelegramBot\Bundle\Client\TelegramClient:
        arguments:
            $httpClient: '@http_client'
            $botToken: '%telegram_bot.token%'
        public: true
