services:
    # Default configuration for services in *this* bundle
    _defaults:
        autowire: true
        autoconfigure: true

    # Automatically register all classes in src/ as services
    Morfeditorial\TelegramBotBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/TelegramBotBundle.php'

    # Register the TelegramClient as a service
    Morfeditorial\TelegramBotBundle\Client\TelegramClient:
        arguments:
            $httpClient: '@http_client'
            $botToken: '%telegram_bot.token%'
        public: true

    Morfeditorial\TelegramBotBundle\Routing\UpdateDispatcher:
        arguments:
            $screens: !tagged_iterator telegram_bot.screen
            $commands: !tagged_iterator telegram_bot.command

    morfeditorial.telegram_bot.security.authenticator:
        class: Morfeditorial\TelegramBotBundle\Security\TelegramWebAppAuthenticator
        abstract: true
        arguments:
            - '' # Token (injected by factory)
            - '' # EventDispatcher (injected by factory)
